### ISSUE TITLE
problem about operating system

### ISSUE THREAD

**Issue by izengpan** [shichaoy/pop_up_image#5]
Hello, your codes were ran in ubuntu14.04+ROS indigo.
Have you ever tried them on ubuntu16.04+ROS?
Thanks for your reply.

**Comment by shichaoy** [comment]
Hi, I haven't tried. I think it should should work. You can post here if you meet problems.

**Comment by izengpan** [comment]
/root/catkin_ws/src/pop_up_image/numpy_opencv/src/utils/conversion.cpp:182:16: error: cannot declare variable ‘g_numpyAllocator’ to be of abstract type ‘NumpyAllocator’
 NumpyAllocator g_numpyAllocator;

--------------------------------------------
have you ever encountered this problem?

**Comment by izengpan** [comment]
/root/catkin_ws/src/pop_up_image/numpy_opencv/src/utils/conversion.cpp:280:16: error: ‘class cv::Mat’ has no member named ‘refcount’
   m.refcount() = refcountFromPyObject(o);
_______________________________________
This is another problem when running the codes.
Please have a look.
thanks

**Comment by shichaoy** [comment]
Hi, numpy_opencv is an external package, I used it just to convert numpy array between opencv mat as there is some small python function I could not find replacement in c++.  I looked at their original repo and found similar problem due to opencv3 as yours: https://github.com/spillai/numpy-opencv-converter/issues/9     seems people provided solution at the end. So maybe you should look at that.

**Comment by izengpan** [comment]
Thanks for your quick reply!
And I have solved my problem with the suggestions.
